TextField: add max and min restrictions to set scrollV too
openfl/openfl pull request #2559
Opened 2022-05-05 18:01 UTC by junsred

add restrictions to scrollV too

2022-05-05 18:13 UTC, dimensionscape commented on src/openfl/text/TextField.hx
> +		if (value < 1) value = 1;
I think this(L#2816) might be handled somewhere else. I can't set scrollV to less than 1 in the latest git.

2022-05-05 18:20 UTC, junsred commented on src/openfl/text/TextField.hx
> +		if (value < 1) value = 1;
Yeah nothing happens in latest git. What needs to happen is it should be set to 1.

2022-05-05 18:22 UTC, Dimensionscape commented on src/openfl/text/TextField.hx
> +		if (value < 1) value = 1;
Ah yeah that makes sense. Cool.

2022-05-05 19:48 UTC, Dimensionscape requested changes
Ah it looks like this is partially handled in TextEngine but the `value>0` check prevents it. Just revert the initial commit and we're good.

2022-05-25 22:12 UTC, junsred commented
@Dimensionscape after reverting my first commit, when i set the scrollV to a number that is higher than max scrollV it becomes max - 1 because of https://github.com/openfl/openfl/commit/f4fcd02408bfd4f0a9c2998bf507feadaddf1572 (Line: 1902) commit.

2022-05-25 22:14 UTC, junsred commented
I don't see my first commit doing any harm.

2022-05-25 22:32 UTC, junsred commented
Oh, I just realized that https://github.com/openfl/openfl/commit/f4fcd02408bfd4f0a9c2998bf507feadaddf1572 is fixed and the code is fine without first commit. I reverted it again. It should be ready for merge.

2022-05-29 21:08 UTC, merged