Adding support in System for hl
openfl/openfl pull request #2561
Opened 2022-05-11 21:14 UTC by Cheemsandfriends

While I was going through System, I noticed that you couldn't check the totalMemory, so I was searching and I found out that it is totally possible to check the memory, (I'm not sure about gc, but it seems like the same)

2022-05-13 08:18 UTC, loudoweb commented
Thanks for your PR. I've made a similar PR one year ago here https://github.com/openfl/openfl/pull/2491. 
But yours seems more complete because you have added gc call, I haven't tested though.
Why to chose `untyped` instead of `int` for memory?

2022-05-13 12:15 UTC, Cheemsandfriends commented
> Why to chose `untyped` instead of `int` for memory?

I was just following what the majority had, which was `untyped`.
But I think it would be better to remove that since hl.Gc seems to be pretty close to neko?

2022-06-29 16:53 UTC, Apprentice-Alchemist requested changes

2022-06-29 16:53 UTC, Apprentice-Alchemist commented on src/openfl/system/System.hx
> +		return Gc.enable(true);
If I remember correctly `Gc.major` is the correct function.
```suggestion
		return Gc.major();
```

2022-06-29 16:53 UTC, Apprentice-Alchemist commented on src/openfl/system/System.hx
> +		return untyped Gc.stats().currentMemory;
```suggestion
		return Std.int(Gc.stats().currentMemory);
```

2023-05-15 15:45 UTC, merged